// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkxmE7JNRfOSSGRgqcuHm-SJuIfQcxunc',
    appId: '1:70275861613:web:bef7a1fe557c412aa54364',
    messagingSenderId: '70275861613',
    projectId: 'feedinsta-7d871',
    authDomain: 'feedinsta-7d871.firebaseapp.com',
    storageBucket: 'feedinsta-7d871.appspot.com',
    measurementId: 'G-XZXLBT9S8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbemxYLOj1HY3ti6Q9c5M49udD6k7LeGc',
    appId: '1:70275861613:android:fe859ddfba1a4e3ca54364',
    messagingSenderId: '70275861613',
    projectId: 'feedinsta-7d871',
    storageBucket: 'feedinsta-7d871.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqENBrynkN5bbO16YUnpG0mQA8u7we9T0',
    appId: '1:70275861613:ios:55f422e6e1806893a54364',
    messagingSenderId: '70275861613',
    projectId: 'feedinsta-7d871',
    storageBucket: 'feedinsta-7d871.appspot.com',
    iosBundleId: 'com.magicsolutionseg.feedinsta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqENBrynkN5bbO16YUnpG0mQA8u7we9T0',
    appId: '1:70275861613:ios:92c4970d8c074033a54364',
    messagingSenderId: '70275861613',
    projectId: 'feedinsta-7d871',
    storageBucket: 'feedinsta-7d871.appspot.com',
    iosBundleId: 'com.magicsolutionseg.feedinsta.RunnerTests',
  );
}
